blank_issues_enabled: false
contact_links:
  - name: Use this repository as a template
    url: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository
    about: Create your own repository rather than filing requests here.